export default {
  home: 'Home',
  upload_image: 'Upload Image',
  photos: 'Photos',
  map: 'Map',
  map_view: 'Map View',
  preview: 'Preview',
  camera: 'Camera',
  gallery: 'Gallery',
  permission_required: 'Permissions Required',
  permission_desc: 'Please allow camera or photo access to upload an image.',
  cancel: 'Cancel',
  open_setting: 'Open Settings',
  latitude: 'Latitude',
  longitude: 'Longitude',
  submit: 'Submit',
  location_error: 'Location Error',
  could_not_get_loc: 'Could not get location.',
  location_permission_req: 'Location permission is required',
  loading: 'Loading...',
  camera_permission_req: 'Camera permission is required to take photos.',
  storage_permission_req:
    'Storage permission is required to select photos from gallery.',
  permission_error: 'Permission Error',
  something_went_wrong_permission:
    'Something went wrong while requesting location permission.',
  location_permission_blocked:
    'Location permission is permanently denied. Open settings to enable it.',
  welcome: 'Welcome!',
  choose_option: 'Choose an option below',
  could_not_fetch_coordinate: 'Could not fetch latitude and longitude.',
  location_permission_denied: 'Location permission denied',
  turn_on_location_service:
    'Turn on Location Services to allow to determine your location.',
  go_to_setting: 'Go to Settings',
  dont_use_location: "Don't Use Location",
  location_denied_by_user: 'Location permission denied by user.',
  location_invoked_by_user: 'Location permission revoked by user.',
};
